name: CI
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{ matrix.pair.elixir }} / OTP ${{ matrix.pair.otp }}
    strategy:
      matrix:
        include:
          - pair:
              elixir: "1.9.4"
              otp: "20.3.8"
          - pair:
              elixir: "1.14.0"
              otp: "25.0.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.pair.elixir }}
          otp-version: ${{ matrix.pair.otp }}

      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('**/mix.lock') }}

      - name: Run CI
        run: mix ci
