name: CI
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    strategy:
      matrix:
        include:
          - otp: '20'
            elixir: '1.9'
          - otp: '25'
            elixir: '1.14'
          - otp: '27'
            elixir: '1.18'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.elixir}}-${{matrix.otp}}-${{ hashFiles('**/mix.lock') }}

      - name: Run CI
        run: mix ci
